version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - todo-service1

  redis:
    image: redis:7.0
    container_name: todo_redis
    ports:
      - "6379:6379"
    networks:
      - todo-service1

  app:
    build: .
    container_name: todo_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=todos
      - REDIS_ADDR=redis:6379
      - REDIS_STREAM=todo-stream
      - SERVER_PORT=8080
    volumes:
      - ./config:/app/config
    command: ["/app/hitrix-todo-app"]
    networks:
      - todo-service1

volumes:
  mysql_data:

networks:
  todo-service1: