-- +migrate Up
CREATE TABLE IF NOT EXISTS outbox_events (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EventType VARCHAR(50) NOT NULL,
    EntityID BIGINT UNSIGNED NOT NULL,
    EntityType VARCHAR(50) NOT NULL,
    Payload TEXT NOT NULL,
    Published BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_published (Published),
    INDEX idx_created_at (CreatedAt)
);

-- +migrate Down
DROP TABLE IF EXISTS outbox_events;
