server:
  timeout_sec: 10
  port: 8080

orm_debug: true

mysql:
  default:
    dsn: "user:password@tcp(mysql:3306)/todo_db?charset=utf8mb4&parseTime=True&loc=Local"
    max_open_conns: 25
    max_idle_conns: 25
    conn_max_lifetime: 5m

redis:
  default:
    addr: "redis:6379"
    db: 0
    pool_size: 10

