package domain

import (
	"git.ice.global/packages/beeorm/v4"
	"time"
)

type TodoItem struct {
	beeorm.ORM  `orm:"table=todos;redisCache"`
	ID          uint64    `orm:"required"`
	Description string    `orm:"required"`
	DueDate     time.Time `orm:"required"`
	CreatedAt   time.Time `orm:"time=true"`
	UpdatedAt   time.Time `orm:"time=true"`
}

func (t *TodoItem) GetID() uint64 {
	return t.ID
}

func (t *TodoItem) SetID(id uint64) {
	t.ID = id
}

func NewTodoItem(description string, dueDate time.Time) TodoItem {
	now := time.Now()
	return TodoItem{
		ID:          0, // Will be auto-generated by database
		Description: description,
		DueDate:     dueDate,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}

func (TodoItem) TableName() string {
	return "todos"
}
